### ISSUE TITLE
Add proper logging

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia-pack#15]
Presently the ersilia pack codebase has a lot of print commands where we should be using console logging. We need to use the native logging library from Python and replace all the prints with a logger.

**Comment by KimFarida** [comment]
@DhanshreeA hi, is this available for the Outreachy Contribution stage?

**Comment by teddyCodex** [comment]
Hi @DhanshreeA Can you assign this to me?

**Comment by DhanshreeA** [comment]
Hi @KimFarida and @teddyCodex both of you alread have issues assigned to you within the ersilia repository.

**Comment by teddyCodex** [comment]
> Hi [@KimFarida](https://github.com/KimFarida) and [@teddyCodex](https://github.com/teddyCodex) both of you alread have issues assigned to you within the ersilia repository.

HI @DhanshreeA Waiting for your feedback on the initial issue assigned to me.

**Comment by MissTife** [comment]
Hi, @DhanshreeA, Can you assign this project to me?

**Comment by DhanshreeA** [comment]
@MissTife yes please go ahead.

**Comment by MissTife** [comment]
Thank you ma.

**Comment by MissTife** [comment]
I have started working on the issue, The first thing I did was to search for the use cases of print, since the task said to remove the prints.
Also I checked if there is a logger used already instead of creating a new one. I found a logging file in the setup requirement file.

**Comment by DhanshreeA** [comment]
> I have started working on the issue, The first thing I did was to search for the use cases of print, since the task said to remove the prints. Also I checked if there is a logger used already instead of creating a new one. I found a logging file in the setup requirement file.

@MissTife which logging file? Also we don't have a setup.py file if that's what you meant.

**Comment by MissTife** [comment]
> > I have started working on the issue, The first thing I did was to search for the use cases of print, since the task said to remove the prints. Also I checked if there is a logger used already instead of creating a new one. I found a logging file in the setup requirement file.
> 
> @MissTife which logging file? Also we don't have a setup.py file if that's what you meant.

I initially forked  the ersilia-os repository instead of the ersilia-pack. I have rectified that and worked on it. Thanks
