### ISSUE TITLE
Edge cases in pip depedency handling

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia-pack#21]
The dependency parser should be extended to handle dependencies of the form:
```
pip install git+https://github.com/bp-kelley/descriptastorus.git@d552f934757378a61dd1799cdb589a864032cd1b
```

Currently it expects four parameters in a pip install command, ie, `pip`, `install`, `dependency`, and `version`. This approach would clearly fail for when wheel files/paths/urls are provided.

**Comment by DhanshreeA** [comment]
Adding to this:

How we end up rewriting the values from a yam to a pip command would also not take into account additional parameters for example, something like,

```
pip install torchvision==0.17.1  --index-url https://download.pytorch.org/whl/cpu
```

**Comment by jubril-adeyi** [comment]
Hi @DhanshreeA , I'd like to take one this issue

**Comment by DhanshreeA** [comment]
Sure, @jubril-adeyi! Assigning you this one as your other issue is close to completion.

**Comment by dzumii** [comment]
@jubril-adeyi How is this going? Any progress?

**Comment by jubril-adeyi** [comment]
@dzumii Thanks for checking in, I’ve been focused on rounding up the previous issue, but I’ll be diving into this one now. I’ll provide a more detailed update shortly as I make progress.

**Comment by jubril-adeyi** [comment]
@DhanshreeA I've been taking some time to digest the parser.py file and understand the different components and their roles. The file contains various classes and methods, each designed to handle parsing and conversion flow. I'm carefully going through each section to get a clear picture of how the logic flows and have a comprehensive understanding before proceeding with any changes.

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

There is a PR open on this. Could you revise and close/merge when you can? Thanks

**Comment by Malikbadmus** [comment]
@DhanshreeA , I'll be taking this issue up.

**Comment by DhanshreeA** [comment]
Hi @Malikbadmus so sorry, but https://github.com/OlawumiSalaam is taking this issue up right now. I didn't manage to tag her in time, but let's give her time to finish this. Could you take up something else?

**Comment by DhanshreeA** [comment]
@OlawumiSalaam you can look into eos4e40 and eos4e41 and use their Dockerfiles as examples - they have both git dependencies and extra args for pip.

**Comment by OlawumiSalaam** [comment]
@DhanshreeA Yes I am on working on the issue.

**Comment by Malikbadmus** [comment]
Oh, I just saw this now. 

I have finished working on it and created a PR just now.

should I close the PR @DhanshreeA ?

**Comment by DhanshreeA** [comment]
No worries @Malikbadmus and thanks for the work! I've merged the PR since your solution was more favorable and I needed this fix urgently. We will streamline contributions moving forward so we don't run into effort duplication.
