### ISSUE TITLE
Add tests for DockerfileInstallParser class

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia-pack#26]

**Comment by OlawumiSalaam** [comment]
@DhanshreeA please can you add a bit of context to this task.  thank you.

**Comment by OlawumiSalaam** [comment]
@DhanshreeA I am still waiting for your approval to work on this issue. Thank you.

**Comment by DhanshreeA** [comment]
Hey @OlawumiSalaam please go ahead!

**Comment by GemmaTuron** [comment]
Hi @OlawumiSalaam and @DhanshreeA 

Please do not work on issues that do not have any description. Detail the steps and which tests will be added in this work.

**Comment by OlawumiSalaam** [comment]
@GemmaTuron I outlined the tests and steps I added in the Pull Request. I will outline it here as well. Thank you.

**Comment by OlawumiSalaam** [comment]
This task is to test parser module with as many edge cases as possible. For parser.py module we want to test Add tests for `DockerfileInstallParser` class. the existing parser module provides classes to parse installation instructions from YAML files and `Dockerfiles`, generate bash scripts from these instructions, and convert metadata from YAML format to JSON. The parser.py has the following classes:

`InstallParser`: An abstract base class for handling installation files. It defines the core functionality for getting the Python executable path, checking for `conda` commands and converting commands to a bash script. It also writes the generated bash script to a file.
`YAMLInstallParser`: Inherits from` InstallParser` and is designed to parse` install.yml` file for Python version and installation commands. It expects the YAML file to have a structure that includes Python version and installation commands.
`DockerfileInstallParser`: Inherits from `InstallParser` and parses a `Dockerfile` for Python version and installation commands. It extracts` RUN pip` or `RUN conda` commands and converts them into a list format.
MetadataYml2JsonConverter: Converts metadata from YAML to JSON. It allows flexible handling of YAML keys and ensures they are converted to JSON in a consistent format.
This task adds unit tests for the `DockerfileInstallParser` class within the Ersilia-pack. The ensures that the class can accurately parse `Dockerfiles` for` pip` and `conda` installation commands and handle various command structures. For context I will add following tests:

- to ensure the `_get_python_version` function retrieves the correct Python version from the Dockerfile.
- to check that `pip install` commands are parsed correctly.
- to validate the parsing of `conda install `commands.

**Comment by DhanshreeA** [comment]
Thanks @OlawumiSalaam ! Here's an example model with an [`install.yml`](https://github.com/ersilia-os/eos3ujl) file that you can use as a test fixture to work on this. And you can any other Ersilia model, for example, this one to use its [Dockerfile](https://github.com/ersilia-os/eos5gge/blob/main/Dockerfile) as a text fixture.

**Comment by OlawumiSalaam** [comment]
@DhanshreeA 
I have added tests for `DockerfileInstallParse`r class. The test_dockerfile_install_parser.py module contains unit tests for the `DockerfileInstallParser` class defined in the dockerfile_install_parser.py module. I used the `pytest` framework to validate that installation commands are correctly parsed from a [Dockerfile](https://github.com/ersilia-os/eos5gge/blob/main/Dockerfile) and also check that the parser correctly interprets Python, pip and conda commands. Here a detailed description of the test is found [here](https://github.com/ersilia-os/ersilia-pack/pull/32) for your review. Thank you.

**Comment by DhanshreeA** [comment]
@OlawumiSalaam I am reviewing the current work, will update here.

**Comment by OlawumiSalaam** [comment]
@DhanshreeA Thank you. I will be waiting for your feedback.

**Comment by P-Mefut** [comment]
Hi @OlawumiSalaam while waiting could you update your repo with the main so as to resolve any merge conflicts when she's done with the review👀🫣

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

This is In Progress but no one is assigned. Is @OlawumiSalaam in charge of that issue? If so let's leave the task assigned to her until it is merged. A timeline should be added to it.
