### ISSUE TITLE
Add tests for YAMLInstallParser class

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia-pack#27]

**Comment by Faith-Adegoke** [comment]
Hello @DhanshreeA, can I be assigned to this issue after my initial PR is merged?

**Comment by OlawumiSalaam** [comment]
@Faith-Adegoke please, are you able to find the `parser.py` module?

**Comment by Faith-Adegoke** [comment]
Yes. 
You can find it here: https://github.com/ersilia-os/ersilia-pack/blob/main/src/ersilia_pack/parsers.py

**Comment by dzumii** [comment]
Well done @Faith-Adegoke, how is it going? can you share an update with us?

**Comment by Faith-Adegoke** [comment]
> Well done @Faith-Adegoke, how is it going? can you share an update with us?

Hello @dzumii. I already made a pull request on the issue. I just referenced it now. Thank you.

**Comment by DhanshreeA** [comment]
@Faith-Adegoke I really like your test cases, but could you please use pytest instead? Many apologies!

**Comment by Faith-Adegoke** [comment]
> @Faith-Adegoke I really like your test cases, but could you please use pytest instead? Many apologies for not clarifying this sooner.

Okay. I will do that.
