### ISSUE TITLE
Add tests for MetadataYml2JsonConverter class

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia-pack#28]
The [MetadataYml2JsonConverter](https://github.com/ersilia-os/ersilia-pack/blob/719d71bd89325920d1c41200415d088353f9e4f6/src/ersilia_pack/parsers.py#L180) utility class converts a metadata.yml file into a JSON format while ensuring the fields follow the type restrictions enforced by the model contribution [template](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/incorporate-models/model-template#the-metadata.yml-file), for example, the field `Task` being enforced as a list, while `Slug` being a string, etc.

We should implement a test for this class using a correct metadata.yml and an incorrect one as test fixtures.

**Comment by adebisi4145** [comment]
Hello @DhanshreeA, I will love to work on this task, can you please assign this task to me.

**Comment by adebisi4145** [comment]
Hello @DhanshreeA, My previous PR has been merged. Could you please assign this to me?

**Comment by DhanshreeA** [comment]
This task has not been taken up by anyone yet, and has no open PRs to tackle it.

**Comment by P-Mefut** [comment]
Hi @DhanshreeA can I pick up this?!

**Comment by DhanshreeA** [comment]
Sure @P-Mefut that would be helpful, thank you. Happy to provide support.

**Comment by P-Mefut** [comment]
Hi @DhanshreeA please do we have a pre-prepared model for this test class?

**Comment by DhanshreeA** [comment]
Hi @P-Mefut, no just a YAML file as a test fixture would suffice.

**Comment by P-Mefut** [comment]
okay thanks @DhanshreeA I'll get right to it!:)

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA and @P-Mefut 

Please when you pick up an issue indicate it on the right hand side by moving the status to "In Progress". Also add a temptative completion deadline.

Thanks!

**Comment by OlawumiSalaam** [comment]
@DhanshreeA I have completed this task and opened a PR for it. Thank you.
