### ISSUE TITLE
Add tests for FastApiAppPacker class

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia-pack#30]
The test cases expected for this class are:

1. Correct initialization - Check whether the `FastApiPacker` object has correctly set attributes given a test model (eg `eos30d7`, or `eos5iy5`). The pytest tmp directory [fixture](https://pytest.org/en/7.4.x/how-to/tmp_path.html) can be utilized to perform these file operations. The attributes such as `dest_dir`, `bundles_repo_path`, `install_writer` are especially of interest here since they govern how the model gets packed. 

2. `_get_model_id` method against i) a JSON file, ii) a YAML file, iii) a gibberish file to assert an exception is raised. 

3. `_get_favicon` - Here the GET request can be mocked to return the file bytes from the favicon.ico file in the repository.

4. `_create_bundle_structure` to see if model files are copied. 

5. `_get_input_schema` to check if the correct template files are copied in the model bundle. 

6. `_get_api_names_from_sh` to check if the api name is correctly parsed. That is, if there's a `run.sh` file, it should return `[run]`.

7. `_create_app_files` to check if the app files are correctly created, including necessary artifacts being copied. 

8. `_edit_post_commands_app` to check for correct parsing and code generation in the `app/main.py` file in the bundle. 

9. `_write_api_schema` to check if the correct api schema is generated given the metadata present within the model.

For now these test cases are a good start, and we can add more here should the need arise.

**Comment by marituhone** [comment]
@DhanshreeA  can u assign it to me?

**Comment by Faith-Adegoke** [comment]
Hello, @DhanshreeA. Can I take this on after my PR on issue #27 is merged?

**Comment by DhanshreeA** [comment]
That's a very good summary of what's happening in the `FastApiPacker` class indeed, @OlawumiSalaam!

**Comment by OlawumiSalaam** [comment]
@DhanshreeA Please kindly provide description for this task as in the test coverage so I can focus on what is necessary.
