### ISSUE TITLE
YAML Parser should raise an error and exit if it cannot determine conda prefix

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia-pack#8]
In the scenario where a user may not have conda initialized in their shell with any environment, even if they have conda binary in their path, the present script to determine the correct conda prefix is not useful.

To clarify:

```Bash
                current_env=$(conda info --envs | grep '*' | awk '{print $1}')
                if [ "$current_env" == "base" ]; then
                    conda_prefix=$CONDA_PREFIX
                else
                    conda_prefix=$CONDA_PREFIX_1
                fi
```

The variable `current_env` is unset if there's no environment running because there is no `*` in the output of `conda info --envs`. This cascades into `source $conda_prefix/etc/profile.d/conda.sh"` not executing and therefore conda not being initialized in the working shell. 

Furthermore, all pip installations begin getting installed in the environment running ersilia-pack, and the conda installs go into the user's base environment. 

Overall, this script requires raising an error, which ersilia-pack should handle appropriately by alerting the user and aborting model packing.

**Comment by KimFarida** [comment]
@DhanshreeA , this also looks interesting. May I?🙉

**Comment by DhanshreeA** [comment]
This is actually addressed in https://github.com/ersilia-os/ersilia-pack/commit/5ef3bf8949255afbb8e5da9749364dfaf3bea25d
