### ISSUE TITLE
Environment installation does not stop on KeyboardInterrupt

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia-pack#9]
If for some reason I wish to terminate the environment installation process, and press `CTRL + C`, the installation does not stop - this is especially happening with conda installs. Each conda install gets started as a new process and with the Keyboard interrupt only the current executing process gets terminated, which is followed by the next install instruction spawning another process until it cycles through all the install instructions.

**Comment by MissTife** [comment]
Hello @DhanshreeA , am I allowed to work on this issue?

**Comment by DhanshreeA** [comment]
Sure @MissTife go ahead!

**Comment by GemmaTuron** [comment]
Hello @DhanshreeA 

There is PR opened on this and not merged. Please update the status of this task.
